name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build
        run: mvn clean package

      - name: Test the package
        run: mvn test
      
      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar
    

  build_image_deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download JAR artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: target/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t tanujarora27/santa-app:latest .

      - name: Run Trivy Scan 
        uses: aquasecurity/trivy-action@master
        with: 
          image-ref : 'tanujarora27/santa-app:latest'
          format: 'table'
          severity : 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '1'
          output: 'trivy-report.txt'
        
      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.txt
      
      - name: Send Trivy Report to the client
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Trivy Scan Report
          body: |
            Trivy Scan Report
          to: ${{ secrets.CLIENT_EMAIL }}
          from: GITHUB ACTIONS
          attachments: trivy-results.txt

      - name: Push Docker image
        run: docker push tanujarora27/santa-app:latest
     