name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build
        run: mvn clean package

      - name: Test the package
        run: mvn test
      
      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar
    

  build_image_deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download JAR artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: target/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t secret-santa .
          docker tag secret-santa:latest tanujarora/secret-santa:latest
          docker push tanujgym/${{secrets.DOCKER_REPO}}:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest